# Generated by Django 5.2 on 2025-04-19 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.CreateModel(
            name='AdditionalResoursesUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('cuorse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='core.course')),
            ],
        ),
    ]
