# Generated by Django 5.2 on 2025-04-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lesson_video_url_additionalresoursesurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons_count',
        ),
    ]
