# Generated by Django 5.2.1 on 2025-05-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_lesson_video_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='add_url1',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_url2',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_url3',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_url4',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
