# Generated by Django 5.2.1 on 2025-05-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lesson_add_url1_lesson_add_url2_lesson_add_url3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='add_url1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='add_url2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='add_url3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='add_url4',
        ),
        migrations.AddField(
            model_name='additionalresoursesurl',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='core.lesson'),
        ),
    ]
